name: Generate 3D Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate 3D Contribution Graph

    steps:
      - uses: actions/checkout@v3

      - name: Generate 3D Contribution Graph
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: MustafaTaweel1
          MAX_REPOS: 10

      - name: Commit & Push
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add -A
          git diff --staged --quiet || git commit -m "chore: update 3D contribution graph"
          git push
